name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Generate release tarball
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          tar czf ov-${VERSION}.tar.gz --transform "s,^,ov-${VERSION}/," --exclude dist *
      - name: Upload release tarball
        uses: softprops/action-gh-release@master
        with:
          files: ov-*.tar.gz
          append_body: true
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
